field: b13628f2-498a-40a3-a301-e5aa3d89815f # Home page buttons
fieldLayouts:
  c5a5c0e1-99cc-4b1c-b07a-923629c7ae07:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: bdf50829-8d56-4739-a3de-37c2c65ebbb0 # Text button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 46c18650-f3e5-48e2-9d0a-cee995b9f0b9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9fc21fc7-5cd2-4df8-a32b-af30bbc6ee10 # Button link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2ffe90bd-4f49-459c-bf18-ac9db758e768
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 46b95784-2b45-4bce-9d31-b138d113a8f7 # color button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 14223945-7e14-4597-87aa-0ee673493f92
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 18427c57-02e6-4be2-ab8c-2303d6cf50be
        userCondition: null
fields:
  9fc21fc7-5cd2-4df8-a32b-af30bbc6ee10: # Button link
    columnSuffix: urrwxehe
    contentColumnType: string(255)
    fieldGroup: null
    handle: buttonLink
    instructions: 'Use this block to link to the movie Who is Ayn.'
    name: 'Button link'
    searchable: false
    settings:
      maxLength: 255
      types:
        - url
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Url
  46b95784-2b45-4bce-9d31-b138d113a8f7: # color button
    columnSuffix: avbtaezh
    contentColumnType: string
    fieldGroup: null
    handle: colorButton
    instructions: 'Select blue for a blue button'
    name: 'color button'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Blue
            -
              - value
              - blue
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Green
            -
              - value
              - green
            -
              - default
              - '1'
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Dropdown
  bdf50829-8d56-4739-a3de-37c2c65ebbb0: # Text button
    columnSuffix: egnohvss
    contentColumnType: text
    fieldGroup: null
    handle: textButton
    instructions: 'How is this button called'
    name: 'Text button'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 1
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
handle: buttonHome
name: ButtonHome
sortOrder: 1
