field: 73966bbe-10c0-4bdf-8bf5-30f8eec4a71d # image
fieldLayouts:
  dc1a8598-7d99-49f6-b98a-7f6b1201d129:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2a5146e9-40c6-41e7-8c80-85f1a379c83a # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: abd62602-b632-44bd-b122-c11eff913a81
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c0f3ae16-6c5c-4dd9-9172-563ce7f28b97 # Link to page
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 584713df-861d-41a8-af0c-241c52ad70f6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d338e87d-f777-4c93-acf9-da8686ae46c4 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b124986b-5336-447d-b093-9ecfc1904192
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6c90d944-8ad4-42e9-9654-cff5d71a2eb5 # Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ef40b48-cf3a-4a8b-96f2-955e8915257c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 21470927-93a4-47ea-b206-a4f25487c06a
        userCondition: null
fields:
  2a5146e9-40c6-41e7-8c80-85f1a379c83a: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      branchLimit: null
      defaultUploadLocationSource: 'volume:17d48411-08a2-41d0-9888-3831ebc5c957' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: true
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:17d48411-08a2-41d0-9888-3831ebc5c957' # Images
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  6c90d944-8ad4-42e9-9654-cff5d71a2eb5: # Subtitle
    columnSuffix: rociosnl
    contentColumnType: string(460)
    fieldGroup: null
    handle: subtitle
    instructions: null
    name: Subtitle
    searchable: false
    settings:
      byteLimit: null
      charLimit: 115
      code: false
      columnType: null
      initialRows: 1
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
  c0f3ae16-6c5c-4dd9-9172-563ce7f28b97: # Link to page
    columnSuffix: kettdhgh
    contentColumnType: string(255)
    fieldGroup: null
    handle: linkTo
    instructions: null
    name: 'Link to page'
    searchable: false
    settings:
      maxLength: 255
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  d338e87d-f777-4c93-acf9-da8686ae46c4: # Title
    columnSuffix: ijhsfmyt
    contentColumnType: text
    fieldGroup: null
    handle: titleImg
    instructions: null
    name: Title
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 1
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\PlainText
handle: imagesEnd
name: ImageDown
sortOrder: 2
