baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: 'Introduction to Objectivism - EN'
primary: true
siteGroup: 0d483e42-f0fe-4fa8-aa13-1cfc8ee3b244 # Introduction to Objectivism
sortOrder: 1
