columnSuffix: qesramyh
contentColumnType: string
fieldGroup: 6203355f-ec05-4011-95a0-d4f0801c79a9 # Home
handle: bodyText
instructions: null
name: 'Body text'
searchable: false
settings:
  contentTable: '{{%matrixcontent_bodytext}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: siteGroup
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
