columnSuffix: azolgkui
contentColumnType: string
fieldGroup: 6203355f-ec05-4011-95a0-d4f0801c79a9 # Home
handle: buttonHome
instructions: 'Put here the link to the ''set up of this site'' movie'
name: 'Home page buttons'
searchable: false
settings:
  contentTable: '{{%matrixcontent_buttonhome}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: siteGroup
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
