columnSuffix: null
contentColumnType: string
fieldGroup: 6203355f-ec05-4011-95a0-d4f0801c79a9 # Home
handle: image
instructions: null
name: image
searchable: false
settings:
  contentTable: '{{%matrixcontent_image}}'
  maxBlocks: 2
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: siteGroup
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
