columnSuffix: arcsjyfr
contentColumnType: text
fieldGroup: 6203355f-ec05-4011-95a0-d4f0801c79a9 # Home
handle: pageTitle
instructions: null
name: 'Page title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 1
  multiline: true
  placeholder: 'Introduction to Objectivism'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
