columnSuffix: uhpfaswy
contentColumnType: text
fieldGroup: 6203355f-ec05-4011-95a0-d4f0801c79a9 # Home
handle: subtitle
instructions: 'Subtitle for the homepage'
name: Subtitle
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 1
  multiline: true
  placeholder: 'Fot those who honestly want to understand'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
