defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  265ed1e3-cc19-48f3-89d9-a079c0f61868: # jan
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
