defaultPlacement: end
enableVersioning: true
handle: page
name: Page
propagationMethod: all
siteSettings:
  265ed1e3-cc19-48f3-89d9-a079c0f61868: # jan
    enabledByDefault: true
    hasUrls: true
    template: page/_entry.twig
    uriFormat: 'page/{slug}'
type: channel
